# Generated by Django 5.2.4 on 2025-07-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicateur",
                    models.CharField(
                        max_length=100, verbose_name="utilisateurs actifs"
                    ),
                ),
                ("valeur", models.FloatField()),
                ("unite_mesure", models.CharField()),
                ("frequence_monitoring", models.CharField()),
                ("date", models.DateField()),
                ("date_debut", models.DateField()),
                ("est_periode", models.BooleanField()),
                ("est_automatise", models.BooleanField()),
            ],
            options={
                "verbose_name": "indicator",
                "verbose_name_plural": "indicators",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_service_public_numerique",
                    models.CharField(max_length=100, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
