# Generated by Django 5.2.4 on 2025-07-25 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indicator",
            options={
                "managed": True,
                "verbose_name": "indicator",
                "verbose_name_plural": "indicators",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "managed": True,
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
    ]
