# Generated by Django 5.2.4 on 2025-07-25 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_indicator_options_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indicator",
            options={"verbose_name": "indicator", "verbose_name_plural": "indicators"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "product", "verbose_name_plural": "products"},
        ),
    ]
