# Generated by Django 5.2.4 on 2025-08-04 09:48

from django.db import migrations, models
from django.template.defaultfilters import slugify


def add_slug_for_existing_products(apps, schema_editor):
    """Compute slug and save it to new 'slug' field for existing products."""
    Product = apps.get_model("core", "Product")

    for product in Product.objects.all():
        product.slug = slugify(product.nom_service_public_numerique)
        product.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_indicator_options_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="default-slug"),
        ),
        migrations.RunPython(
            add_slug_for_existing_products, reverse_code=migrations.RunPython.noop
        ),
    ]
