# Generated by Django 5.2.4 on 2025-08-06 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_productapikey"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indicator",
            options={
                "ordering": ("-date",),
                "verbose_name": "indicator",
                "verbose_name_plural": "indicators",
            },
        ),
    ]
