# Generated by Django 5.2.4 on 2025-10-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_indicator_created_at_indicator_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicator",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="date and time at which a record was created",
                verbose_name="created at",
            ),
        ),
    ]
