# Generated by Django 5.2.8 on 2026-02-02 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_indicator_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adaptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indicator", models.CharField()),
                ("source_url", models.CharField(blank=True, null=True)),
                (
                    "method",
                    models.CharField(
                        help_text="name of the method used to fetch data",
                        verbose_name="data fetching method",
                    ),
                ),
                ("status", models.CharField()),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "last_successful_run",
                    models.DateTimeField(
                        editable=False, verbose_name="last successful run"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adaptor",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adaptor",
                "verbose_name_plural": "Adaptors",
                "db_table": "adaptor",
                "unique_together": {("product", "indicator")},
            },
        ),
    ]
