# Generated by Django 5.2.8 on 2025-12-05 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_indicator_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adaptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(help_text='name of the method used to fetch data', verbose_name='data fetching method')),
                ('indicator', models.CharField()),
                ('productid', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.PROTECT, related_name='adaptor', to='core.product')),
            ],
            options={
                'verbose_name': 'Adaptor',
                'verbose_name_plural': 'Adaptors',
                'db_table': 'adaptor',
            },
        ),
    ]
