# Generated by Django 5.2.8 on 2026-03-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_indicator_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicator",
            name="est_automatise",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="est_periode",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="frequence_monitoring",
            field=models.CharField(default="monthly"),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="unite_mesure",
            field=models.CharField(default="unités"),
        ),
    ]
