# Generated by Django 5.2.8 on 2026-02-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_adaptor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adaptor",
            name="last_successful_run",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="last successful run",
            ),
        ),
    ]
