# Generated by Django 5.2.8 on 2025-12-05 17:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_adaptor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adaptor',
            old_name='productid',
            new_name='product',
        ),
        migrations.AddField(
            model_name='adaptor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='date and time at which a record was created', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adaptor',
            name='status',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adaptor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated at'),
        ),
        migrations.AlterUniqueTogether(
            name='adaptor',
            unique_together={('product', 'indicator')},
        ),
    ]
