# Generated by Django 5.2.8 on 2025-12-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_productid_adaptor_product_adaptor_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptor',
            name='url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
