# Generated by Django 5.2.8 on 2026-05-11 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_adaptor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adaptor",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_column="product",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adaptor",
                to="core.product",
            ),
        ),
    ]
