# Generated by Django 5.2.8 on 2026-05-11 13:14

import django.db.models.deletion
from django.db import migrations, models


def compute_indicators_slugs(apps, schema_editor):
    """Copy all existing records to the new model."""
    Indicator = apps.get_model("core", "Indicator")
    for indicator in Indicator.objects.all():
        indicator.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_adaptor_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="slug",
            field=models.SlugField(default="defaultslug"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="adaptor",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_column="product",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adaptor",
                to="core.product",
            ),
        ),
        migrations.RunPython(
            compute_indicators_slugs,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
