# Generated by Django 5.2.8 on 2026-05-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_indicator_slug_alter_adaptor_product"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="indicator",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="indicator",
            constraint=models.UniqueConstraint(
                fields=("productid", "indicateur", "frequence_monitoring", "date"),
                name="unique_username",
            ),
        ),
    ]
