# Generated by Django 5.2.8 on 2026-05-27 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_all_indicators_to_new_model(apps, schema_editor):
    """Copy all existing records to the new model."""
    Indicator = apps.get_model("core", "Indicator")
    Record = apps.get_model("core", "Record")

    for indicator in Indicator.objects.all():
        Record.objects.create(
            indicator=indicator,
            value=indicator.valeur,
            end_date=indicator.date,
            start_date=indicator.date_debut,
            is_auto_added=indicator.est_automatise,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_indicator_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("value", models.FloatField()),
                ("end_date", models.DateField()),
                ("start_date", models.DateField(blank=True, null=True)),
                ("is_auto_added", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        db_column="indicator",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="core.indicator",
                    ),
                ),
            ],
            options={
                "verbose_name": "record",
                "verbose_name_plural": "records",
                "db_table": "record",
                "ordering": ("-end_date",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("indicator", "end_date", "start_date"),
                        name="unique_record_for_indicator_and_dates",
                    )
                ],
            },
        ),
        migrations.RunPython(
            copy_all_indicators_to_new_model,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
