# Generated by Django 5.2.8 on 2026-05-26 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_indicator_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Indicator",
            new_name="Record",
        ),
    ]
