# Generated by Django 5.2.8 on 2026-05-26 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_rename_indicator_record"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="record",
            options={
                "ordering": ("-date",),
                "verbose_name": "record",
                "verbose_name_plural": "records",
            },
        ),
        migrations.RenameField(
            model_name="adaptor",
            old_name="indicator",
            new_name="record",
        ),
        migrations.AlterField(
            model_name="record",
            name="productid",
            field=models.ForeignKey(
                db_column="productId",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="records",
                to="core.product",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="adaptor",
            unique_together={("product", "record")},
        ),
        migrations.AlterModelTable(
            name="record",
            table="record",
        ),
    ]
