# Generated by Django 5.2.8 on 2026-07-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_record"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="indicator",
            name="unique_username",
        ),
        migrations.AddConstraint(
            model_name="indicator",
            constraint=models.UniqueConstraint(
                fields=("productid", "indicateur", "frequence_monitoring", "date"),
                name="no_duplicate_indicators",
            ),
        ),
    ]
