# Generated by Django 5.2.8 on 2026-07-09 11:23

from django.db import migrations


def deduplicate_indicators(apps, schema_editor):
    """Regroup all related records under a single indicator object. Delete remaining unused indicators."""
    Indicator = apps.get_model("core", "Indicator")
    Record = apps.get_model("core", "Record")

    all_indicators = list(set([(indicator.indicateur, indicator.productid) for indicator in Indicator.objects.all()]))

    for indicator in all_indicators:
        related_indicators = Indicator.objects.filter(indicateur=indicator[0], productid=indicator[1])
        deduplicated_indicator = related_indicators.first()
        Record.objects.filter(indicator__indicateur=indicator[0], indicator__productid=indicator[1]).update(indicator=deduplicated_indicator)

        [indicator.delete() for indicator in related_indicators[1:]]

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_indicator_unique_username_and_more'),
    ]

    operations = [
        migrations.RunPython(
            deduplicate_indicators,
        ),
    ]
