# Generated by Django 5.2.8 on 2026-05-26 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_record_options_rename_indicator_adaptor_record_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Adaptor",
            new_name="Indicator",
        ),
    ]
