# Generated by Django 5.2.8 on 2026-05-26 12:37

import django.db.models.deletion
from django.db import migrations, models


def compute_indicators_slugs(apps, schema_editor):
    """Names of our models have been chambouled. Compute name from associated 'record' (former indicator)
    and slug automatically from name."""
    Indicator = apps.get_model("core", "Indicator")
    Record = apps.get_model("core", "Record")
    for indicator in Indicator.objects.all():
        indicator.name = indicator.record
        indicator.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_rename_adaptor_indicator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indicator",
            options={"verbose_name": "Indicator", "verbose_name_plural": "Indicators"},
        ),
        migrations.AlterUniqueTogether(
            name="indicator",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="indicator",
            name="name",
            field=models.CharField(default="default_name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="indicator",
            name="slug",
            field=models.SlugField(default="default_slug"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="indicator",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_column="product",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="indicator",
                to="core.product",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="indicator",
            unique_together={("product", "name")},
        ),
        migrations.AlterModelTable(
            name="indicator",
            table="indicator",
        ),
        migrations.RunPython(
            compute_indicators_slugs,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
