# Generated by Django 5.2.8 on 2026-07-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_deduplicate_indicators'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='unique_record_for_indicator_and_dates',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nom_service_public_numerique',
            new_name='name',
        ),
    ]
