# Generated by Django 5.2.8 on 2026-07-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_record_unique_record_for_indicator_and_dates_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='indicator',
            name='no_duplicate_indicators',
        ),
        migrations.AddConstraint(
            model_name='indicator',
            constraint=models.UniqueConstraint(fields=('productid', 'indicateur', 'frequence_monitoring'), name='no_duplicate_indicators'),
        ),
    ]
