# Generated by Django 5.2.8 on 2026-07-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_unique_constraint_on_indicators'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('indicator', 'end_date'), name='no_duplicate_records'),
        ),
    ]
