# Generated by Django 5.2.8 on 2026-08-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_unique_constraint_on_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='valeur',
        ),
    ]
