# Generated by Django 5.2.8 on 2026-08-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_indicator_valeur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ('-updated_at',), 'verbose_name': 'indicator', 'verbose_name_plural': 'indicators'},
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='date',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='date_debut',
        ),
    ]
