# Generated by Django 5.2.8 on 2026-08-31 17:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_indicator_options_remove_indicator_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTSatisfactionLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plis', models.UUIDField(default=uuid.uuid4, verbose_name='id_plis')),
                ('date', models.DateField()),
                ('commentaire', models.CharField(blank=True, null=True)),
                ('note', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('type_satisfaction', models.CharField(choices=[('Download', 'download_satisfaction'), ('Upload', 'upload_satisfaction')])),
                ('domaine', models.CharField()),
                ('is_demo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FTUsageLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plis', models.UUIDField(default=uuid.uuid4)),
                ('date', models.DateField()),
                ('domaine_expediteur', models.CharField()),
                ('domaine_destinataire', models.CharField()),
                ('is_demo', models.BooleanField(default=False)),
            ],
        ),
    ]
