[project]
name = "OPI-stats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asgiref==3.12.1",
    "datagouv-client==0.5.0",
    "dj-database-url==3.1.2",
    "django==6.0.7",
    "django-dsfr==3.5.2",
    "djangorestframework==3.17.1",
    "djangorestframework-api-key==3.1.0",
    "drf-spectacular==0.30.0",
    "drf-spectacular-sidecar==2026.7.1",
    "factory-boy==3.3.3",
    "freezegun==1.5.5",
    "gunicorn==26.0.0",
    "pandas==3.0.5",
    "psycopg2-binary==2.9.12",
    "pytest==9.1.1",
    "pytest-django==4.14.0",
    "python-dotenv==1.2.2",
    "responses==0.26.2",
    "ruff==0.16.1",
    "sqlparse==0.5.5",
    "typing-extensions==4.16.0",
    "whitenoise==6.12.0",
]


[tool.ruff]
exclude = ["migrations"]